### ISSUE TITLE
import/export/copy/paste package manager addresses + settings

### ISSUE THREAD

**Issue by serapath** [playproject-io/playproject-io.github.io#14]
## `@todo`
* [ ] specifytechnical infrastructure for settings/import/export mechanisms
* [ ] describe usage scenarios in OS
* [ ] make abstract UI/UX concept for how to show those in the app

---

### technical infrastructure
* ...

### usage scenarios
* ...

### UI/UX concept
* ...
