### ISSUE TITLE
Update - Playproject Improvements 

### ISSUE THREAD

**Issue by ibrarli** [playproject-io/playproject-io.github.io#20]
## `@todo`

- [ ] Update - Playproject Improvements
  - `@input` 📦 
    - [Playproject.io](https://playproject.io/)
    - Improvements for Playproject from [`comment`](https://github.com/playproject-io/playproject-io.github.io/issues/20#issuecomment-2155833648)

---

- [x] Design - big project island for a project called "Wizard Amigos"
 - `@input` 📦  
   - [playproject.io](https://playproject.io/)
   - [Blender 3d asset of Wizard Amigos](https://github.com/wizardamigos/assets/tree/main/3D)
   - [Павел Беседин worklog - 30](https://www.youtube.com/watch?v=7xf38kRoyyU)
   - [Павел Беседин worklog - 31](https://www.youtube.com/watch?v=Fy3vNs8yyNM)
- Rough Sketch of Island
- Outline the sketch on Illustrator 
- Adding details on the island 
- refining and finalizing the island
- `output`: 📦 [wizard-amigos Island v2](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=9-2&t=lKd7NdZg9VkTpox2-4) from [comment](https://github.com/playproject-io/playproject-io.github.io/issues/20#issuecomment-2180390653) 

---

- [ ] Design - big project island for a project called "data shell"
 - `@input` 📦  [playproject.io](https://playproject.io/)

---

- [ ] Design - a project island for the "task messenger app"
 - `@input` 📦  [playproject.io](https://playproject.io/)

---

- [x] Design - a night theme for playproject 
 - `@input` 📦  [playproject.io](https://playproject.io/)
 - a background with different night gradient 
 - stars in the sky
 - even planets
 - `@output` 📦 [playproject-night theme v1](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=59-5306&t=zQiSqFfKR7LDXxcl-4) from [`comment`](https://github.com/playproject-io/playproject-io.github.io/issues/20#issuecomment-2195243770)

---

- [X] Design - a variety for team islands 
 - `@input` 📦  [playproject.io](https://playproject.io/)
 - sponsor islands are already different in style same thing for team island
 - `@ouput` 📦 [team islands](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=27-11&t=uzmzcPUjaNIWub5t-4) from [`comment`](https://github.com/playproject-io/playproject-io.github.io/issues/20#issuecomment-2191985558)

---

- [ ] Update - add more animation effect for top main island 
 - `@input` 📦  [playproject.io](https://playproject.io/)
 - rotating windmills 
 - animals moving around
 -  a waterfall that animated where some drops drop from the island above onto the next.
 - if islands in general very subtly float and move up and down by themselves... like a boat on a sea with some calm waves

---
- [X] Design - logo for Data Shell
 - `@input` 📦 [data-shell server](https://discord.com/channels/1203761949603799152/1203762774648291328)
 - Designed two version of logo for data shell
 - `@output` 📦 [data-shell v1](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=80-6&t=HMUKkDisOG71kwSj-4) from [`comment`](https://github.com/playproject-io/playproject-io.github.io/issues/20#issuecomment-2198452097)
 - `@output` 📦 [data-shell v2](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=80-5&t=HMUKkDisOG71kwSj-4) from [`comment`](https://github.com/playproject-io/playproject-io.github.io/issues/20#issuecomment-2198452097)
---
- [ ] Design - logo for Task management app

**Comment by ibrarli** [comment]
### tasks - `2024.06.07`

- Update - Playproject Improvements
  - PlayProject website QA Research - `23 min`
  - Took Screenshots and presented feedback - `50 min`
  - Logged Task - `6 min`
--- 

### worklog

---

### feedback
 - 1 - We have supporters text out here I don't know if its intentional or by mistake <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/e0179bde-9fd8-41a7-a666-9ae6ead7ea61" alt="Image Description" width="600"/>
  - 2 - This picture is quite pixilated and not readable <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/1c1657fe-56c6-4aff-9649-ecb7534d6c89" alt="Image Description" width="600"/>
  - 3 - Mail icon is upside down <br><img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/a7e459c5-5924-4707-8d8e-86309e0db964" alt="Image Description" width="300"/>
  - 4 - Twitter icon is outdated <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/7d7aaca9-105c-4513-8f38-f34bf7ad48ba" alt="Image Description" width="300"/>
  - 5 - Is it suppose to be 2023 like is it a date of establishing of playproject? <br>
<img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/84231d7c-7999-46dc-8ef7-e4678d02fc2d" alt="Image Description" width="600"/><br>
  - 6 - While scrolling through contributor section left side looks empty which makes it seem a bit off if we could make start of left container sticky somehow Or we could shift some on left side<br><img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/27ad14f8-e1df-41b2-9ec1-1411447d577c" alt="Image Description" width="600"/> <br>
  - 7 - I think this is intentional but there is no main menu below 768X832 dimension <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/40aaaf11-a185-4e93-a047-498e78e61369" alt="Image Description" width="600"/>
  - 8 - On same screen ratio  squirrel is hovering over text <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/c624fdfa-9fc6-482c-95ec-4a8746b2cb5a" alt="Image Description" width="300"/>
  - 9 - On Mobile dimensions is mostly shifted mostly toward right Like e is cutting <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/645a3851-6070-4c09-8fc2-30729737f9fd" alt="Image Description" width="300"/> <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/be1c1f0f-0813-4c16-ac77-902634b0be6f" alt="Image Description" width="300"/> <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/cbbc8b68-bf3e-4790-90cd-dfadd1c9b7e7" alt="Image Description" width="300"/> <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/b6ef8ceb-d1ed-456b-8153-f9cce21f6ad4" alt="Image Description" width="300"/> 
- 10 - This section is above each other <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/7766a093-318c-4fb1-ba3f-23fc60d219d4" alt="Image Description" width="300"/>
- 11 - On my phone it looks centered but on inspect it looks toward right a bit  <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/35574eb1-333e-4252-a9d0-313cd4f7cf4c" alt="Image Description" width="300"/>
- 12 - OTHER THAN that it looks fine on other dimensions We can maybe play with paddings a little bit

---

### proposals

**Comment by serapath** [comment]
1. double checked and yes that is intentional. It is meant to be the "title" for the section and maybe this should be shown in a different way, e.g. another island or some sort of wodden sign on an island or something to indicate what this section is about.

2. you can try to make a good screenshot from this video, which is the only thing we have at the moment: https://x.com/ninabreznik/status/1170132016504946688

3. yes, let's fix the email icon

4. yes, let's fix the x icon and probably make it black with a white X

5. nope, the year at the bottom should be the current year, so based on current Date. Ali can fix the javascript logic to update the year to always show the current year :-)

6. yes, this is a big issue and some people are missing. Like David, Ali, You, Cypher, ... those are generated from a data file that lists all data of contributors and will probably grow in the future, so it would be good if we can find a nice balanced layout or way to always display everyone in a better way :-)

7. true - interesting observation. maybe it's okay? i guess if somebody looks for contacts, they have to scroll to the bottom? ...do you have any good ideas how we could integrate that on mobile in a nice way? maybe a bottom menu to not be so awkward to reach?

8. another nice observation. yeah, maybe if we can prevent the squirrel from being covred by the text would probably be great too :-)

9.  yes, we should definitely improve the overall experience with that and work also on the font layout and readability on all resolutions, maybe even switch fonts or whatever... feel free to try to improve that as well :-)

10. wow, another good catch, yes they should probably not touch each other i guess. ...if possible and still readable, maybe they could even dynamically "shrink" in size when on mobile so more fits on the screen?

11. yeah lets fix it and also, now seeing the mobile version, maybe the main island can shrink as well to fit on the screen? (but only when cut off)

12. yes, please fine tune some paddings and other paramters for improving things, potentially the smoothness of animations as well and if you think some of the images can be improved, that would be interesting too.

----

Lastly, we have another island that is completly missing and we need to design it. We sadly don't have a low poly island for it, but only a 3D design and two worklogs which show it.
Otherwise, if you have blender you can open the original 3D designs ...it's a "Wizardamigos Island" :-)

**Comment by serapath** [comment]
**feedback `2024.06.09`**

It sounds good. Let's try that.
I do think we actually need to slowly use and get active by creating pull requests and changing all the above inside the current page.

Maybe for the wizardamigos island section (i can share the 3D assets and youtube worklogs that show them), we need some concept and maybe for some other minor aspects we need some figma as well, but for most things we probably need to directly update the actual page css code.

**Comment by ibrarli** [comment]
### tasks - `2024.06.09`

- Update - Playproject Improvements
  - Presenting Proposal for playproject changes - `30 min`
--- 

### worklog

---

### feedback

---

### proposals
- 1 - we can use the same island just change the text to supporters <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/81505e2f-efce-45c9-9291-a5e97caf738d" alt="Image Description" width="300"/> <br>
- 2 - This is not the best quality but way better then the existing one <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/f45c96d6-e68d-4f11-af5d-15f31cf726a3" alt="Image Description" width="900"/> <br>
- 3 - I think we can do it this way  
-      transform-origin: center;
       transform: rotate(180deg);
- 4 -  We can use the same github one all we would have to change is x icon but we would have to change placement because i don't think two black icon together will look consistent <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/d67cccf5-14b9-428f-99b8-ff03e09c66e8" alt="Image Description" width="300"/> <br>
- 5 - I think it is all what it needs  
- var currentYear = new Date().getFullYear();
    var text = currentYear + " Playproject";
    document.getElementById("footertext").textContent = text;
- 6 - I will try to find some better layout but for now what I have in mind is to keep first 3 as it is and change other into full screen no empty place in left and divide them into four columns like 4 islands in one row 
- 7 - One way it is possible to do in mobile would be to use menu at bottom like this icons is optional <br> <img src="https://github.com/playproject-io/playproject-io.github.io/assets/106898965/fc0416d7-140c-40e9-809a-0621bcb44e01" alt="Image Description" width="300"/> <br>
- 8 - we can play with padding here 
- 9 - yup definitely we could discuss and find some way to better optimize for most of the screen 
- 10 - we can play with padding here but shrinking also works 
- 11 - yup we can find someway to stop overflowing and for images to automatically adjust according to screen 
- 12 - I will look more into see if there are places we can make more improvement will discuss with you in discord
- 13 - Yup I have seen that before can you provide more brief into it like where are we going to use it and for it to be designed as exact as 3d model but in low poly like in 3d one it has a lot of details they are to be omit from low poly

**Comment by ibrarli** [comment]
### tasks - `2024.06.16`

- Update - Playproject Improvements
  - Island For Wizard Amigos 
    - Rough Sketch of Island - `40 min`
    - Outline the sketch on Illustrator - `45 min`
    - Filling the outlines with color - `50 min`
    - Illustrating trees on island  x 3 - `35 min`
    - adding details on the island - `30 min`
  - logging task - `10 min`
  - output 📦 [`wizard amigos Island`](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=1-2&t=ZsFFBqEVLWTgKeyA-4)
--- 

### worklog
- [`worklog-22`](https://youtu.be/tiH77lmzt4M)
---

### feedback

---

### proposals

**Comment by ibrarli** [comment]
### tasks - `2024.06.19`

- Update - Playproject Improvements
  - replicating 3d wizard amigos Island to low poly design for playproject.io 
    - designing 2 dome - `40 min`
    - designing better library/hangout space dome - `55 min`
    - designing new replicate tree  - `40 min`
    - designing big advertisement banner for wizard amigos website  - `24 min`
    - refining and adding details such as stones, bushes, shadow details, and boulder under dome - `20 min`  
  - logging task - `10 min`
  - output 📦 [`wizard amigos Island v2`](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=9-2&t=lKd7NdZg9VkTpox2-4)
--- 

### worklog

---

### feedback
 - I have tried to replicate as exact to wizard amigos 3d island also keeping the vibe with other existing island on playproject same so also if you want to include more details in Island do let me know we can make it more highlighted and add more shades or shadows. or grass etc. I have also included bill board type for wizard amigos website if its small we can make it bigger also if you have any better way do let me know  
---

### proposals

**Comment by ibrarli** [comment]
### tasks - `2024.06.25`

- Design - a variety for team islands
  - `@input` 📦 [playproject.io](https://playproject.io/)
  - team island Variation 1
    - Rough Sketch of Island - `20 min`
    - designing base of island in adobe illustrator - `35 min`
    - Designing elements of island  (tree and log) - `20 min`
    - output 📦 [team-island v1](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=27-12&t=e6Wjt2J0YXkhYy4z-4)
  - team island Variation 2
    - Rough sketch of design - `20 min`
    - designing base of island in adobe illustrator - `40 min`
    - designing elements of island (tree + Crystal) - `40 min`
    - output 📦 [team-island v2](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=27-14&t=e6Wjt2J0YXkhYy4z-4)
  - team island Variation 3
    - Rough sketch of design - `17 min`
    - designing base of island in adobe illustrator - `35 min`
    - designing elements of island (tree + bush) - `30 min`
    - output 📦 [team-island v3](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=27-15&t=RzJ0BWT2pq9VofPK-4)
  - team island Variation 4
    - Rough sketch of design - `10 min`
    - desiging elements of island (tree + crystal) - `40 min`
    - output 📦 [team-island v4](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=29-2&t=RzJ0BWT2pq9VofPK-4)
  - team island Variation 5
     - Rough sketch of design - `12 min`
    - desiging elements of island (tree + rock) - `35 min`
    - output 📦 [team-island v5](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=29-4&t=RzJ0BWT2pq9VofPK-4)
  - team island Variation 6
      - Rough sketch of design - `11 min`
     - desiging elements of island (tree + log) - `30 min`
    - output 📦 [team-island v6](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=29-5&t=RzJ0BWT2pq9VofPK-4)
  - team island Variation 7
      - Rough sketch of design - `10 min`
      - desiging elements of island (tree + rock) - `35 min`
    - output 📦 [team-island v7](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=29-6&t=RzJ0BWT2pq9VofPK-4)
  - logging task - `15 min`
  - output 📦 [`team islands`](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=27-11&t=e6Wjt2J0YXkhYy4z-4)
--- 

### worklog
- [worklog-23](https://youtu.be/nPphcSC0yrs)
---

### feedback

---

### proposals

**Comment by ibrarli** [comment]
### tasks - `2024.06.26`

- Design - a night theme for playproject
  - `@input` 📦 [playproject.io](https://playproject.io/)
  - Design - Planet Earth - `1 hr`
    - Rough Sketch of Planet
    - designing planet in adobe illustrator
    - Detailing of planet
    - output 📦 [planet-earth](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=61-611&t=zQiSqFfKR7LDXxcl-4)
  - Design - Planet Mercury - `45 min`
    - Rough Sketch of Planet
    - designing planet in adobe illustrator
    - Detailing of planet
    - output 📦 [planet-mercury](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=61-43&t=zQiSqFfKR7LDXxcl-4)
  - Design - Planet Neptune- `50 min`
    - Rough Sketch of Planet
    - designing planet in adobe illustrator
    - Detailing of planet
    - output 📦 [planet-neptune](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=61-2&t=zQiSqFfKR7LDXxcl-4)
  - Design - Moon - `45 min`
    - Rough Sketch of Moon
    - designing Moon in adobe illustrator
    - Detailing of Moon
    - output 📦 [moon](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=61-795&t=zQiSqFfKR7LDXxcl-4)
  - Design - Star - `10 min`
    - desiging Star in adobe Illustrator
    - output 📦 [Star](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=61-840&t=zQiSqFfKR7LDXxcl-4)
  - Supporter Island
      - Rough sketch of design - `11 min`
      - Designing island in adobe illustrator - `20 min`
     - desiging element of island (tree) - `25 min`
    - output 📦 [supporter-island](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=61-841&t=zQiSqFfKR7LDXxcl-4)
  - Redisgn - twitter logo 
      - designing twitter logo in adobe illustrator - `10 min`
    - output 📦 [twitter logo](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=61-842&t=zQiSqFfKR7LDXxcl-4)
  - logging task - `10 min`
--- 

### worklog

---

### feedback
- For this worklog I have designed elements that are discussed earlier with alex for night theme. Next I will put this elements on playproject night theme webpage
---

### proposals

**Comment by ibrarli** [comment]
### tasks - `2024.06.27`

- Design - a night theme webpage for playproject
  - `@input` 📦 [playproject.io](https://playproject.io/)
  - Replicating the existing illustrations and contents from playproject website in figma - `2 hr 35 min`
  - Creating gradient dark background - `5 min`
  - Putting stars in design - `30 min`
  - Putting planets in design - `10 min`
  - Making adjustment in supporters, teams section and overall design - `50 min`
  - logging task - `15 min`
  - `@output` 📦 [playproject-night theme v1](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=59-5306&t=zQiSqFfKR7LDXxcl-4)
--- 

### worklog
- [`worklog-24`](https://youtu.be/mXMyYayM-Ig)
---

### feedback

---

### proposals

**Comment by ibrarli** [comment]
### tasks - `2024.06.29`
---
- Design - logo for Data Shell
  - `@input` 📦 [data-shell server](https://discord.com/channels/1203761949603799152/1203762774648291328)
  - Data Shell - Logo Version 1 only turtle shell 
    - Sketching the turtle shell - `45 min`
    - Illustrating the turtle shell in adobe illustrator - `1hr 30 min`
    - Coloring and adjusting the color and extra detailing for low poly shadows - `1 hr`
    - `@output` 📦 [Data Shell - v1](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=80-6&t=HMUKkDisOG71kwSj-4)
  - Data Shell - Logo Version 2 full turtle 
    - Sketching the rest of turtle body - `40 min`
    - Illustrating the rest of turtle and adjusting with turtle shell in adobe illustrator - `40 min`
    - Coloring and adjusting the color for low poly shadows - ` 30 min`
    - `@output` 📦 [Data Shell - v2](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=80-5&t=HMUKkDisOG71kwSj-4)
  - logging task - `5 min`
--- 

### worklog

---

### feedback
- I have created two logo version one with only shell and other with full turtle. I have upload exported  version in figma you can check and let me know if any improvement needs to be made.
---

### proposals

**Comment by ibrarli** [comment]
### tasks - `2024.06.30`
---
- Design - big project island for a project called "data shell"
  - `@input` 📦 [data-shell server](https://discord.com/channels/1203761949603799152/1203762774648291328)
  - Data Shell - Logo Version 1 only turtle shell 
    - Sketching the turtle- `2hr`
    - Illustrating the turtle  in adobe illustrator - `1hr 20 min`
    - Coloring and adjusting the color and extra detailing for low poly shadows - `1 hr 21min`
    - `@output` 📦 [Data Shell - Turtle](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=87-3&t=nzj8GEIQgh0klaDU-4)
  - logging task - `5 min`
--- 

### worklog

---

### feedback
- I have created a turtle for Data Shell Island which can also be used for logo as well. Next will be working on island it self
---

### proposals
- I am thinking of designing an aquarium island in which turtles will float and include other sea components such as stone sea plants etc.

**Comment by ibrarli** [comment]
### tasks - `2024.06.30`
---
- Design - big project island for a project called "data shell"
  - `@input` 📦 [data-shell server](https://discord.com/channels/1203761949603799152/1203762774648291328)
  - Data Shell - island 
    - Sketching the island itself and its tank and sand - `2 hr`
    - Illustrating the  island adobe illustrator - `1hr 30 min`
    - Coloring and adjusting the color and extra detailing ( island itself and its tank and sand) - `1hr 10 min`
    - `@output` 🏭  [Data shell - island v1](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=109-2&t=PORo9kYREFMtDGpZ-4)
  - logging task - `5 min`
--- 

### worklog

---

### feedback
- This is still on progress there are more details remaining
---

### proposals

**Comment by ibrarli** [comment]
### tasks - `2024.07.01`
---
- Design - big project island for a project called "data shell"
  - `@input` 📦 [data-shell server](https://discord.com/channels/1203761949603799152/1203762774648291328)
  - Data Shell - island 
    - Illustrating the ship adobe illustrator - `1hr 40 min`
    - Illustrating the plants adobe illustrator - `1hr`
    - Illustrating the stones adobe illustrator - `2hr`
    - Illustrating the fish adobe illustrator - `1hr 10 min`
    - Adjust all in the aquarium - `20 min`
    - `@output` 📦   [Data shell - island v2](https://www.figma.com/design/K7KQwutTcz2ejz30k7vACt/Untitled?node-id=109-4&t=PORo9kYREFMtDGpZ-4)
  - logging task - `5 min`
--- 

### worklog

---

### feedback
- This is complete for now if you have any recommendation please share
---

### proposals
