### ISSUE TITLE
Create - graph_explorer

### ISSUE THREAD

**Issue by alyhxn** [playproject-io/playproject-io.github.io#32]
## `@todo`

#21 

- [ ] Create - `graph_explorer`
   - [x] Implement base
   - [x] Iterations with different designs and structures
   - [x] Implement stable graph structure (finalized if more changes are not proposed)
   - [ ] Highlight selected entry's lineage in `graph_explorer`
   - [ ] Interactions and buttons inside the graph
   - [ ] Lazy loading
   - [ ] Test with big data
   - [ ] List vs tree architecture, tree is easy to implement, list is better for big data and lazy loading.
   - `@output` :question: `graph_explorer_v0.0.?`
      - next #21

**Comment by alyhxn** [comment]
### Tasks - `2024.11.07`

- Update - `graph_explorer_v0.0.1`
   - Implement compact mode - `3h`
   - Update colors and highlights for duplicates - `1h30min`
   - Import and export - `2h`
   - Recorded Worklog - `10min`
   - Logged tasks - `5min`
   - `@output` :package: [graph_explorer_v0.0.1](https://github.com/playproject-io/playproject-io.github.io/commit/15697bd297d16167c059a46c3cdc1fa29d3fd402)

--- 
### Worklog
[worklog-242](https://youtu.be/ZhVtC4NG0Ss)

**Comment by serapath** [comment]
**feedback `2024.11.07`**


### 1. color highlighting
+1 for duplicate highlighting :-) awesome.

---

### 2. compact/normal graph explorer modes

Just kidding, but hmm, this seems a misunderstanding :-)

The "compact mode" is what i expect "normal mode" to be and the "compact mode" does not exist, but instead we have:

![old mode](https://imgur.com/GUkLExF.png)

Here are example of what i imagine compact mode and normal mode to be:

**compact:**
```
🪄┱🌐playproject.io/
  ┠─📁pins/
  ┃┌─🌐playproject.io/
  ┠┼📁themes/
  ┃├─🎨fantasy.json
  ┃├─🎨electro.json
  ┃├─🎨light.json
  ┃│┌─📁themes/
  ┃└┼🎨night.json📍
  ┃ ├─🔗page:css
  ┃ ├─🔗page/header:css
  ┃ ├─🔗page/header/menu:css
  ┃ │┌─🎨night.json
  ┃ ├┼🔗page/projects:css
  ┃ │├─🖌️header.css
  ┃ │└─🖌️1.css
  ┃ ├─🔗page/footer:css
  ┃ └─🔗page/footer/socials:css
  ┃┌─🇹page
  ┃├─🎨night.json
  ┗╅🧩playproject-io
   ┠─🧩theme-widget
   ┠─🧩topnav
```
**normal:**
```
🌐┱playproject.io/
  ┠📁─pins/
  ┃  ┌🌐─playproject.io/
  ┠📁┼themes/
  ┃  ├🎨─fantasy.json
  ┃  ├🎨─electro.json
  ┃  ├🎨─light.json
  ┃  │  ┌📁─themes/
  ┃  └🎨┼night.json📍
  ┃     ╞🔗─page:css
  ┃     ├🔗─page/header:css
  ┃     ├🔗═page/header/menu:css
  ┃     │  ┌🎨─night.json
  ┃     ├🔗┼page/projects:css
  ┃     │  ├🖌️─header.css
  ┃     │  └🖌️─1.css
  ┃     ├🔗─page/footer:css
  ┃     └🔗─page/footer/socials:css
  ┃  ┌🇹─page
  ┃  ├🎨─night.json
  ┗🧩╅playproject-io
     ┠🧩─theme-widget
     ┠🧩─topnav
```

**Comment by alyhxn** [comment]
### Tasks - `2024.11.14`

- Update - `graph_explorer_v0.0.1`
   - Fixed the normal structure - `1h`
   - `@output` :package: [graph_explorer_v0.0.2](https://github.com/playproject-io/playproject-io.github.io/commit/fc4de61f3d3164d5d44042f6b61530f70c5e2ada#diff-4a9ab497d843cddcf4ac8aae78f3b90e1b69f20e5dfd3749114ca50256ea5d95)

### Worklog
[worklog-243](https://youtu.be/pK6fCNxh7Bg)

**Comment by serapath** [comment]
**feedback `2024.11.20`**
```
🌐┱playproject.io/
  ┠📁─pins/  # normal mode
```
```
🪄┱🌐playproject.io/
  ┠─📁pins/  # compact mode
```
The idea is you can either click the icon :file_folder: or you can click the line `─` to expand it.
1. clicking the first expands subs entries
2. clicking the second expands super entries

What we have now is only one click that always expands BOTH (super and sub) at the same time.
That wasnt the goal.

Can we fix that please? :slight_smile:
