### ISSUE TITLE
add social media preview (twitter, facebook, ...)

### ISSUE THREAD

**Issue by serapath** [playproject-io/playproject-io.github.io#4]
## `@todo`
* [ ] when somebody pastes a link to our page on twitter or facebook or somewhere, we need to show a preview
* [ ] check:
  * https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fsmartcontract.codes
  * https://stackoverflow.com/a/26537086
* [ ] use maybe:
  * http://www.page2images.com/
  * to get something like: http://api.page2images.com/ccimages/b6/f8/n6ckdxRiD0E7rQOP.png
* [ ] research twitter card options
* [ ] research facebook card options
* [ ] research others (e.g. instagram, tiktok?, snapchat?, ...)
* [ ] make concept for **preview card** for different play apps
* [ ] implement facebook card
* [ ] implement twitter card

---
reading materials:
* check result https://cards-dev.twitter.com/validator
* check result https://developers.facebook.com/tools/debug/og/object/
* https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
* https://developers.facebook.com/docs/sharing/webmasters
* more https://sproutsocial.com/insights/twitter-cards-guide/
* old https://davidwalsh.name/twitter-cards
