### ISSUE TITLE
website improvements

### ISSUE THREAD

**Issue by serapath** [playproject-io/playproject-io.github.io#9]
## `@todo`

---
## `@later`
* [ ] maybe make menu bar item texts a bit more visible?
* [ ] make project description texts a bit bigger/bolder and maybe color white
* [ ] add social media icons to profiles and read links from profile json files
  * what about just `contact: '...'` or `website: '...'` instead of `contact: { website, github, twitter}`

---
